# Generated by Django 4.0.4 on 2022-04-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favoright_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(1, 'Delivery'), (2, 'Repair'), (3, 'Other')]),
        ),
    ]
