# Generated by Django 4.0.4 on 2022-04-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favoright_app', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
